"""add_max_materials_to_system_config

Revision ID: 25924036fa48
Revises: 859275581d84
Create Date: 2026-07-18 23:51:40.711811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25924036fa48'
down_revision: Union[str, Sequence[str], None] = '859275581d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('system_configs', sa.Column('max_materials', sa.Integer(), nullable=True))
    op.execute("UPDATE system_configs SET max_materials = 5 WHERE max_materials IS NULL")
    op.alter_column('system_configs', 'max_materials', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configs', 'max_materials')
    # ### end Alembic commands ###
