"""add_model_name_to_system_config

Revision ID: 859275581d84
Revises: a1b2c3d4e5f6
Create Date: 2026-07-18 23:39:47.277614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859275581d84'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('system_configs', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.execute("UPDATE system_configs SET model_name = '' WHERE model_name IS NULL")
    op.alter_column('system_configs', 'model_name', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_configs', 'model_name')
    # ### end Alembic commands ###
