"""add cascade delete to user foreign keys

Revision ID: 959ce1f568aa
Revises: 25924036fa48
Create Date: 2026-07-19 00:23:49.513537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959ce1f568aa'
down_revision: Union[str, Sequence[str], None] = '25924036fa48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('exam_papers_teacher_id_fkey'), 'exam_papers', type_='foreignkey')
    op.create_foreign_key(None, 'exam_papers', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('llm_configs_teacher_id_fkey'), 'llm_configs', type_='foreignkey')
    op.create_foreign_key(None, 'llm_configs', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('materials_user_id_fkey'), 'materials', type_='foreignkey')
    op.create_foreign_key(None, 'materials', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notes_user_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('quizzes_user_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('student_llm_configs_teacher_id_fkey'), 'student_llm_configs', type_='foreignkey')
    op.drop_constraint(op.f('student_llm_configs_student_id_fkey'), 'student_llm_configs', type_='foreignkey')
    op.create_foreign_key(None, 'student_llm_configs', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_llm_configs', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uni_info_teacher_id_fkey'), 'uni_info', type_='foreignkey')
    op.create_foreign_key(None, 'uni_info', 'users', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uni_info', type_='foreignkey')
    op.create_foreign_key(op.f('uni_info_teacher_id_fkey'), 'uni_info', 'users', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'student_llm_configs', type_='foreignkey')
    op.drop_constraint(None, 'student_llm_configs', type_='foreignkey')
    op.create_foreign_key(op.f('student_llm_configs_student_id_fkey'), 'student_llm_configs', 'users', ['student_id'], ['id'])
    op.create_foreign_key(op.f('student_llm_configs_teacher_id_fkey'), 'student_llm_configs', 'users', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_user_id_fkey'), 'quizzes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_user_id_fkey'), 'notes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.create_foreign_key(op.f('materials_user_id_fkey'), 'materials', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'llm_configs', type_='foreignkey')
    op.create_foreign_key(op.f('llm_configs_teacher_id_fkey'), 'llm_configs', 'users', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'exam_papers', type_='foreignkey')
    op.create_foreign_key(op.f('exam_papers_teacher_id_fkey'), 'exam_papers', 'users', ['teacher_id'], ['id'])
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
