"""add_system_config_fields_to_llm_config

Revision ID: c2a4013107c6
Revises: 0d1628d4da08
Create Date: 2026-07-19 19:49:08.711662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a4013107c6'
down_revision: Union[str, Sequence[str], None] = '0d1628d4da08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_configs', sa.Column('system_prompt', sa.Text(), nullable=True))
    op.add_column('llm_configs', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('llm_configs', sa.Column('top_p', sa.Float(), nullable=True))
    op.add_column('llm_configs', sa.Column('frequency_penalty', sa.Float(), nullable=True))
    op.add_column('llm_configs', sa.Column('presence_penalty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_configs', 'presence_penalty')
    op.drop_column('llm_configs', 'frequency_penalty')
    op.drop_column('llm_configs', 'top_p')
    op.drop_column('llm_configs', 'temperature')
    op.drop_column('llm_configs', 'system_prompt')
    # ### end Alembic commands ###
